"""ADD tokensCount

Revision ID: 0d9d703f4acc
Revises: f1149087792e
Create Date: 2024-04-19 20:44:39.766667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9d703f4acc'
down_revision = 'f1149087792e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_activity', 'inputTokens')
    op.drop_column('chat_activity', 'outputTokens')
    op.add_column('message', sa.Column('tokensCount', sa.BigInteger(), nullable=True, default=0))
    op.execute('UPDATE message SET "tokensCount" = 0 WHERE "tokensCount" IS NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'tokensCount')
    op.add_column('chat_activity', sa.Column('outputTokens', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('chat_activity', sa.Column('inputTokens', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
