"""Init

Revision ID: 19880331cb2f
Revises: 
Create Date: 2024-05-02 16:19:13.543335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19880331cb2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    chat_type = sa.Enum('private', 'group', 'supergroup', name='chat_type_enum')
    currentGptModel = sa.Enum('gpt-3.5-turbo-0125', 'gpt-4', name='chat_gptmodel_enum')

    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('chatName', sa.String(), nullable=True),
    sa.Column('chatType', chat_type, server_default='private', nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('referredBy', sa.String(), nullable=True),
    sa.Column('referralUsers', sa.JSON(), nullable=True),
    sa.Column('currentGptModel', currentGptModel, nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatId')
    )
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apikeyPosition', sa.Integer(), nullable=True),
    sa.Column('isBeta', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freeapikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apiKey', sa.String(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=True),
    sa.Column('requests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('limit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monthlyLimitImage', sa.Integer(), nullable=True),
    sa.Column('monthlyLimitGpt3', sa.Integer(), nullable=True),
    sa.Column('monthlyLimitGpt4', sa.Integer(), nullable=True),
    sa.Column('monthlyLimitTranslation', sa.Integer(), nullable=True),
    sa.Column('limitOutputTokens', sa.Integer(), nullable=True),
    sa.Column('limitInputTokens', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    message_type = sa.Enum('message', 'image', name='message_type_enum')
    role = sa.Enum('user', 'system', 'assistant', name='role_enum')
    model_enum = sa.Enum('gpt-3.5-turbo-0125', 'gpt-4', 'lexica', name='model_enum')

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('role', role, nullable=True),
    sa.Column('messageType', message_type, nullable=True),
    sa.Column('uzMessage', sa.Text(), nullable=True),
    sa.Column('tokensCount', sa.BigInteger(), nullable=True),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('isCleaned', sa.Boolean(), nullable=True),
    sa.Column('model', model_enum, nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planId', sa.UUID(), nullable=True),
    sa.Column('currentPeriodStart', sa.DateTime(), nullable=True),
    sa.Column('currentPeriodEnd', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('isCanceled', sa.Boolean(), nullable=True),
    sa.Column('canceledAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('allMessages', sa.BigInteger(), nullable=True),
    sa.Column('translatedMessagesCount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chat.chatId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('additionalGpt3Requests', sa.BigInteger(), nullable=True),
    sa.Column('additionalGpt4Requests', sa.BigInteger(), nullable=True),
    sa.Column('additionalImageRequests', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chat.chatId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amountForMonth', sa.BigInteger(), nullable=True),
    sa.Column('isFree', sa.Boolean(), nullable=True),
    sa.Column('isGroup', sa.Boolean(), nullable=True),
    sa.Column('limitId', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['limitId'], ['limit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan')
    op.drop_table('chat_quota')
    op.drop_table('chat_activity')
    op.drop_table('subscription')
    op.drop_table('message')
    op.drop_table('limit')
    op.drop_table('freeapikey')
    op.drop_table('configuration')
    op.drop_table('chat')
    op.drop_table('admin')
    # ### end Alembic commands ###
