"""CHANGED

Revision ID: 2335ca408085
Revises: 97487671573f
Create Date: 2024-01-13 23:46:26.487925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2335ca408085'
down_revision = '97487671573f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('apikey_position', sa.Integer(), nullable=True))
    op.drop_column('configuration', 'freeapikey_position')
    op.add_column('freeapikey', sa.Column('is_expired', sa.Boolean(), nullable=True))
    op.drop_column('freeapikey', 'is_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freeapikey', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('freeapikey', 'is_expired')
    op.add_column('configuration', sa.Column('freeapikey_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('configuration', 'apikey_position')
    # ### end Alembic commands ###
