"""ADD: added message isCleaned field

Revision ID: 270220b141e8
Revises: 0d9d703f4acc
Create Date: 2024-04-27 00:38:03.445890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270220b141e8'
down_revision = '0d9d703f4acc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('isCleaned', sa.Boolean(), default=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'isCleaned')
    # ### end Alembic commands ###
