"""INIT

Revision ID: 2db169427f6d
Revises: 
Create Date: 2024-01-13 20:53:52.275573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db169427f6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_stats', 'todays_entered_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_stats', sa.Column('todays_entered_request', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
