"""REMOVED

Revision ID: 38a65a1ca7ba
Revises: 514af6ef8ceb
Create Date: 2024-01-29 23:59:48.215933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a65a1ca7ba'
down_revision = '514af6ef8ceb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'autoTranslate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('autoTranslate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
