"""Added translatedMessagesCount

Revision ID: 39108faa8640
Revises: a7e6ee0ac1f3
Create Date: 2024-03-15 21:57:16.301632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39108faa8640'
down_revision = 'a7e6ee0ac1f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_activity', sa.Column('translatedMessagesCount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_activity', 'translatedMessagesCount')
    # ### end Alembic commands ###
