"""ADD: added freeapikey

Revision ID: 40de99cdf53c
Revises: 2db169427f6d
Create Date: 2024-01-13 21:09:12.280839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40de99cdf53c'
down_revision = '2db169427f6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freeapikey',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freeapikey')
    # ### end Alembic commands ###
