"""Added translateCount to limit

Revision ID: 41b599e9d2c3
Revises: ac4d50a5415c
Create Date: 2024-04-27 23:45:41.138085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b599e9d2c3'
down_revision = 'ac4d50a5415c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limit', sa.Column('monthlyLimitedTranslateRequests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('limit', 'monthlyLimitedTranslateRequests')
    # ### end Alembic commands ###
