"""Changed model fields

Revision ID: 48df0e6baa74
Revises: acf6082034a8
Create Date: 2024-04-18 15:21:03.523879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48df0e6baa74'
down_revision = 'acf6082034a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_activity', sa.Column('todayMessages', sa.BigInteger(), nullable=True, default=0))
    op.add_column('chat_activity', sa.Column('todayImages', sa.BigInteger(), nullable=True, default=0))
    op.drop_column('chat_activity', 'todaysMessages')
    op.drop_column('chat_activity', 'todaysImages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_activity', sa.Column('todaysImages', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('chat_activity', sa.Column('todaysMessages', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('chat_activity', 'todayImages')
    op.drop_column('chat_activity', 'todayMessages')
    # ### end Alembic commands ###
