"""Changes

Revision ID: 4b7e9666407f
Revises: 41b599e9d2c3
Create Date: 2024-04-29 18:30:23.419675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7e9666407f'
down_revision = '41b599e9d2c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    chat_gptmodel_enum = sa.Enum('gpt-3.5-turbo-0125', 'gpt-4', name='chat_gptmodel_enum')
    model_enum = sa.Enum('gpt-3.5-turbo-0125', 'gpt-4', 'lexica', name='model_enum')

    chat_gptmodel_enum.create(op.get_bind(), checkfirst=False)
    model_enum.create(op.get_bind(), checkfirst=False)

    op.add_column('chat', sa.Column('currentGptModel', chat_gptmodel_enum, nullable=True))
    op.add_column('chat_quota', sa.Column('additionalGpt3Requests', sa.BigInteger(), nullable=True))
    op.add_column('chat_quota', sa.Column('additionalGpt4Requests', sa.BigInteger(), nullable=True))
    op.drop_column('chat_quota', 'additionalGptRequests')
    op.add_column('limit', sa.Column('monthlyLimitImage', sa.Integer(), nullable=True))
    op.add_column('limit', sa.Column('monthlyLimitGpt3', sa.Integer(), nullable=True))
    op.add_column('limit', sa.Column('monthlyLimitGpt4', sa.Integer(), nullable=True))
    op.add_column('limit', sa.Column('monthlyLimitTranslation', sa.Integer(), nullable=True))
    op.add_column('limit', sa.Column('limitOutputTokens', sa.Integer(), nullable=True))
    op.add_column('limit', sa.Column('limitInputTokens', sa.Integer(), nullable=True))
    op.drop_column('limit', 'monthlyLimitedImageRequests')
    op.drop_column('limit', 'monthlyLimitedTranslateRequests')
    op.drop_column('limit', 'monthlyLimitedGptRequests')
    op.add_column('message', sa.Column('model', model_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'model')
    op.add_column('limit', sa.Column('monthlyLimitedGptRequests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('limit', sa.Column('monthlyLimitedTranslateRequests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('limit', sa.Column('monthlyLimitedImageRequests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('limit', 'limitInputTokens')
    op.drop_column('limit', 'limitOutputTokens')
    op.drop_column('limit', 'monthlyLimitTranslation')
    op.drop_column('limit', 'monthlyLimitGpt4')
    op.drop_column('limit', 'monthlyLimitGpt3')
    op.drop_column('limit', 'monthlyLimitImage')
    op.add_column('chat_quota', sa.Column('additionalGptRequests', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('chat_quota', 'additionalGpt4Requests')
    op.drop_column('chat_quota', 'additionalGpt3Requests')
    op.drop_column('chat', 'currentGptModel')
    # ### end Alembic commands ###
