"""INIT

Revision ID: 520bcf9bc779
Revises: 
Create Date: 2024-01-19 00:05:20.223892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520bcf9bc779'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatName', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('isActivated', sa.Boolean(), nullable=True),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('autoTranslate', sa.Boolean(), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatId')
    )
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apikeyPosition', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freeapikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apiKey', sa.String(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=True),
    sa.Column('requests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('user', 'system', 'assistant', name='role_enum'), nullable=True),
    sa.Column('uzMessage', sa.Text(), nullable=True),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('amountForWeek', sa.BigInteger(), nullable=True),
    sa.Column('isFree', sa.Boolean(), nullable=True),
    sa.Column('weeklyLimitedImageRequests', sa.Integer(), nullable=True),
    sa.Column('weeklyLimitedGptrequests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planId', sa.UUID(), nullable=True),
    sa.Column('currentPeriodStart', sa.DateTime(), nullable=True),
    sa.Column('currentPeriodEnd', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('cardholder', sa.String(), nullable=True),
    sa.Column('isCanceled', sa.Boolean(), nullable=True),
    sa.Column('canceledAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messageStats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('outputTokens', sa.BigInteger(), nullable=True),
    sa.Column('inputTokens', sa.BigInteger(), nullable=True),
    sa.Column('allMessages', sa.BigInteger(), nullable=True),
    sa.Column('todaysImages', sa.BigInteger(), nullable=True),
    sa.Column('todaysMessages', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chat.chatId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messageStats')
    op.drop_table('subscription')
    op.drop_table('plan')
    op.drop_table('message')
    op.drop_table('freeapikey')
    op.drop_table('configuration')
    op.drop_table('chat')
    op.drop_table('admin')
    # ### end Alembic commands ###
