"""Changed the field and removed unnecessary fields

Revision ID: 5c2991de5c04
Revises: 7ba5c7d688d5
Create Date: 2024-02-02 00:13:44.547895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2991de5c04'
down_revision = '7ba5c7d688d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('outputTokens', sa.BigInteger(), nullable=True),
    sa.Column('inputTokens', sa.BigInteger(), nullable=True),
    sa.Column('allMessages', sa.BigInteger(), nullable=True),
    sa.Column('todaysImages', sa.BigInteger(), nullable=True),
    sa.Column('todaysMessages', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chat.chatId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('additionalGptRequests', sa.BigInteger(), nullable=True),
    sa.Column('additionalImageRequests', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chat.chatId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_activity')
    op.drop_column('chat', 'isActivated')
    op.add_column('plan', sa.Column('monthlyLimitedGptRequests', sa.Integer(), nullable=True))
    op.add_column('plan', sa.Column('isGroup', sa.Boolean(), nullable=True))
    op.add_column('plan', sa.Column('isHostGroup', sa.Boolean(), nullable=True))
    op.drop_column('plan', 'monthlyLimitedGptrequests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('monthlyLimitedGptrequests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('plan', 'isHostGroup')
    op.drop_column('plan', 'isGroup')
    op.drop_column('plan', 'monthlyLimitedGptRequests')
    op.add_column('chat', sa.Column('isActivated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('user_activity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chatId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('outputTokens', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('inputTokens', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('allMessages', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('todaysImages', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('todaysMessages', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('gptRequests', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chat.chatId'], name='user_activity_chatId_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_activity_pkey')
    )
    op.drop_table('chat_quota')
    op.drop_table('chat_activity')
    # ### end Alembic commands ###
