"""Added messageType

Revision ID: 5dfd9351842e
Revises: 8ae2396992ad
Create Date: 2024-04-19 17:32:42.146962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfd9351842e'
down_revision = '8ae2396992ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_activity', 'translatedMessagesCount',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('chat_activity', 'todayMessages')
    op.drop_column('chat_activity', 'todayImages')
    message_type = sa.Enum('message', 'image', name='message_type_enum')
    message_type.create(op.get_bind(), checkfirst=True)
    op.add_column('message', sa.Column('messageType', message_type,
                                       nullable=True, default='message'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'messageType')
    op.add_column('chat_activity', sa.Column('todayImages', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True))
    op.add_column('chat_activity', sa.Column('todayMessages', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True))
    op.alter_column('chat_activity', 'translatedMessagesCount',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
