"""Added plan description

Revision ID: 73787a61ff5b
Revises: e13209d922c9
Create Date: 2024-04-27 19:13:52.006169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73787a61ff5b'
down_revision = 'e13209d922c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'description')
    # ### end Alembic commands ###
