"""Changed the messageStat to chatActivity

Revision ID: 7ba5c7d688d5
Revises: 38a65a1ca7ba
Create Date: 2024-02-01 18:20:11.623914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba5c7d688d5'
down_revision = '38a65a1ca7ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=True),
    sa.Column('outputTokens', sa.BigInteger(), nullable=True),
    sa.Column('inputTokens', sa.BigInteger(), nullable=True),
    sa.Column('allMessages', sa.BigInteger(), nullable=True),
    sa.Column('todaysImages', sa.BigInteger(), nullable=True),
    sa.Column('todaysMessages', sa.BigInteger(), nullable=True),
    sa.Column('gptRequests', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chat.chatId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('messageStats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messageStats',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"messageStats_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('chatId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('outputTokens', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('inputTokens', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('allMessages', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('todaysImages', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('todaysMessages', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chat.chatId'], name='messageStats_chatId_fkey'),
    sa.PrimaryKeyConstraint('id', name='messageStats_pkey')
    )
    op.drop_table('user_activity')
    # ### end Alembic commands ###
