"""ADD: added freeapikey

Revision ID: 97487671573f
Revises: 40de99cdf53c
Create Date: 2024-01-13 21:41:45.215372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97487671573f'
down_revision = '40de99cdf53c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freeapikey_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration')
    # ### end Alembic commands ###
