"""IsBeta is added

Revision ID: a7e6ee0ac1f3
Revises: 5c2991de5c04
Create Date: 2024-03-02 00:44:11.528060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e6ee0ac1f3'
down_revision = '5c2991de5c04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('isBeta', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'isBeta')
    # ### end Alembic commands ###
