"""Added chatType field

Revision ID: ab07e2a6a69b
Revises: 39108faa8640
Create Date: 2024-04-14 01:01:01.104065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab07e2a6a69b'
down_revision = '39108faa8640'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    chat_type = sa.Enum('private', 'group', 'supergroup', name='chat_type_enum')
    chat_type.create(op.get_bind(), checkfirst=True)
    op.add_column('chat', sa.Column('chatType', chat_type, nullable=True, server_default='private'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'chatType')
    # ### end Alembic commands ###
