"""Removed cardholder field

Revision ID: ac4d50a5415c
Revises: 73787a61ff5b
Create Date: 2024-04-27 22:42:05.756096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4d50a5415c'
down_revision = '73787a61ff5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'cardholder')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('cardholder', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
