"""Added limit model

Revision ID: acf6082034a8
Revises: ab07e2a6a69b
Create Date: 2024-04-17 18:53:40.272570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf6082034a8'
down_revision = 'ab07e2a6a69b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monthlyLimitedImageRequests', sa.Integer(), nullable=True),
    sa.Column('monthlyLimitedGptRequests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('plan', sa.Column('limitId', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'plan', 'limit', ['limitId'], ['id'])
    op.drop_column('plan', 'monthlyLimitedImageRequests')
    op.drop_column('plan', 'isHostGroup')
    op.drop_column('plan', 'monthlyLimitedGptRequests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('monthlyLimitedGptRequests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plan', sa.Column('isHostGroup', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('plan', sa.Column('monthlyLimitedImageRequests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plan', type_='foreignkey')
    op.drop_column('plan', 'limitId')
    op.drop_table('limit')
    # ### end Alembic commands ###
